name: Build and Upload Artifact

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build IG with docker builder
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          docker.kodality.com/fsh-builder \
          /bin/bash -c "cd /workspace && ./_genonce.sh"
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: output/
